language: android
android:
  components:
    - platform-tools
    - tools    
    - build-tools-23.0.3
    - android-23
    - extra
before_install:
  - gpg --batch --passphrase $GPG_DECRYPTION_KEY google-credentials.json.gpg
  - gpg --batch --passphrase $GPG_DECRYPTION_KEY keystore.jks.gpg
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &